name: musaic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.9.0
  - aom=3.5.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - audioread=3.0.1
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.0
  - cpp-expected=1.1.0
  - cpython=3.9.23
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=5.1.2
  - filelock=3.18.0
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - fqdn=1.5.1
  - freetype=2.13.3
  - fsspec=2025.5.1
  - gettext=0.24.2
  - gettext-tools=0.24.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarchive=3.8.1
  - libasprintf=0.24.2
  - libasprintf-devel=0.24.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.7
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.2
  - libgettextpo-devel=0.24.2
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.24.2
  - libintl-devel=0.24.2
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.3.0
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.49
  - libprotobuf=5.29.3
  - librosa=0.10.2.post1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsolv=0.7.33
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libunistring=0.9.10
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - llvmlite=0.43.0
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.3.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nlohmann_json=3.11.3
  - nomkl=1.0
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=2.0.2
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openssl=3.5.1
  - optree=0.16.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - pooch=1.8.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytorch=2.7.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.26.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=78.1.1
  - simdjson=3.13.0
  - six=1.17.0
  - sleef=3.8
  - sniffio=1.3.1
  - soupsieve=2.7
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - sqlite=3.45.2
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - sympy=1.14.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - madmom==0.17.dev0
      - mido==1.3.3
